TARGET = iphone:clang:latest:5.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = StillCapture2iOS456

StillCapture2iOS456_FILES = Tweak.xm
StillCapture2iOS456_FRAMEWORKS = AVFoundation UIKit CoreGraphics MediaPlayer
StillCapture2iOS456_INSTALL_PATH = /Library/Application Support/SC2
StillCapture2iOS456_LIBRARIES = substrate

include $(THEOS_MAKE_PATH)/library.mk
