#!/bin/sh

chk=$(uname -m)

if [[ "$chk" == "iPod4,1" ]] || [[ "$chk" == iPhone3* ]] || [[ "$chk" == "iPhone4,1" ]];then
	cd /System/Library/PrivateFrameworks/PhotoLibrary.framework
	mv -f PLCameraVideoStillCaptureIconPressed_2only_-568h@2x~ipad.png PLCameraVideoStillCaptureIconPressed_2only_-568h@2x~iphone.png
	mv -f PLCameraVideoStillCaptureIcon_2only_-568h@2x~ipad.png PLCameraVideoStillCaptureIcon_2only_-568h@2x~iphone.png
fi

if [ -d "/System/Library/PrivateFrameworks/PhysicsKit.framework" ];then
	cd /System/Library/PrivateFrameworks/PhotoLibrary.framework
	rm -f PLCameraVideoStillCaptureIcon*
fi

exit
