TARGET = iphone:clang:latest:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = StillCapture2iOS789

StillCapture2iOS789_FILES = Tweak.xm
StillCapture2iOS789_FRAMEWORKS = CoreGraphics UIKit
StillCapture2iOS789_LIBRARIES = MobileGestalt substrate
StillCapture2iOS789_INSTALL_PATH = /Library/Application Support/SC2

include $(THEOS_MAKE_PATH)/library.mk
